In [110]:
import numpy as np

# 4D array in the format of [month[week[day[min,max]]]]
# Month in the order of Nov,Dec,Jan & Feb.
# Weeks in the oreder of W1,W2,W3 & W4.
# Days in the order of Mon,Tue,Wed,Thu,Fri,Sat & Sun

temp=np.array([[[[6,23],[14,20],[6,27],[14,22],[8,22],[6,32],[14,29]],[[7,27],[12,29],[11,29],[-13,23],[15,28],[15,20],[8,32]],[[5,21],[12,18],[-1,12],[12,20],[25,29],[17,22],[12,19]],[[-2,15],[0,12],[2,18],[13,24],[10,16],[12,18],[0,17]]],[[[8,23],[14,20],[6,27],[14,22],[8,22],[6,32],[14,29]],[[7,27],[12,29],[11,29],[-15,23],[15,31],[15,30],[8,30]],[[5,21],[12,18],[-12,12],[12,20],[25,27],[17,28],[12,19]],[[-2,15],[0,12],[2,18],[13,24],[10,20],[12,24],[0,17]]],[[[9,23],[14,20],[6,27],[14,22],[8,22],[6,32],[14,29]],[[7,27],[12,29],[11,29],[15,23],[-13,31],[15,30],[8,30]],[[5,21],[12,18],[-1,12],[12,20],[25,27],[17,28],[12,19]],[[-2,15],[0,12],[2,18],[13,24],[10,20],[12,24],[0,17]]],[[[6,23],[14,20],[6,27],[14,22],[8,22],[6,32],[14,29]],[[7,27],[12,29],[11,29],[-13,23],[15,31],[15,30],[8,30]],[[5,21],[12,18],[-1,12],[12,20],[25,27],[17,28],[12,19]],[[-2,15],[0,12],[2,18],[13,24],[10,20],[12,24],[0,17]]]])

month=['November','December','January','February']
day=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']

print(temp)

[[[[  6  23]
   [ 14  20]
   [  6  27]
   [ 14  22]
   [  8  22]
   [  6  32]
   [ 14  29]]

  [[  7  27]
   [ 12  29]
   [ 11  29]
   [-13  23]
   [ 15  28]
   [ 15  20]
   [  8  32]]

  [[  5  21]
   [ 12  18]
   [ -1  12]
   [ 12  20]
   [ 25  29]
   [ 17  22]
   [ 12  19]]

  [[ -2  15]
   [  0  12]
   [  2  18]
   [ 13  24]
   [ 10  16]
   [ 12  18]
   [  0  17]]]


 [[[  8  23]
   [ 14  20]
   [  6  27]
   [ 14  22]
   [  8  22]
   [  6  32]
   [ 14  29]]

  [[  7  27]
   [ 12  29]
   [ 11  29]
   [-15  23]
   [ 15  31]
   [ 15  30]
   [  8  30]]

  [[  5  21]
   [ 12  18]
   [-12  12]
   [ 12  20]
   [ 25  27]
   [ 17  28]
   [ 12  19]]

  [[ -2  15]
   [  0  12]
   [  2  18]
   [ 13  24]
   [ 10  20]
   [ 12  24]
   [  0  17]]]


 [[[  9  23]
   [ 14  20]
   [  6  27]
   [ 14  22]
   [  8  22]
   [  6  32]
   [ 14  29]]

  [[  7  27]
   [ 12  29]
   [ 11  29]
   [ 15  23]
   [-13  31]
   [ 15  30]
   [  8  30]]

  [[  5  21]
   [ 12  18]
   [ -1  12]
   [ 12  20]
   [ 25  27]
 

In [174]:
print(f'Dimension: {temp.ndim}')
print(f'Shape: {temp.shape}')

Dimension: 4
Shape: (4, 4, 7, 2)


In [60]:
print(f'# In the format of [month[week 1[day[min,max]]]] :\n{temp[:,0,:]}')

# In the format of [month[week 1[day[min,max]]]] :
[[[ 6 23]
  [14 20]
  [ 6 27]
  [14 22]
  [ 8 22]
  [ 6 32]
  [14 29]]

 [[ 8 23]
  [14 20]
  [ 6 27]
  [14 22]
  [ 8 22]
  [ 6 32]
  [14 29]]

 [[ 9 23]
  [14 20]
  [ 6 27]
  [14 22]
  [ 8 22]
  [ 6 32]
  [14 29]]

 [[ 6 23]
  [14 20]
  [ 6 27]
  [14 22]
  [ 8 22]
  [ 6 32]
  [14 29]]]


In [175]:
print('Day wise temperature:')

# Shape of temp is (4,4,7,2)
for i in range(temp.shape[0]):   # iterate over Months
    
    j=0  # iterate over Weeks.here, only week-1 required
    print(f'\t{month[i]} / Week-1')
    
    for k in range(temp.shape[2]):   # iterate over Days
        print(f'{day[k]}')
       
        # 'l' iterate over Temperature
        l=0   # access min 
        print(f' *Min-{temp[i,j,k,l]}',chr(176),'C')
        
        l=l+1 # access max 
        print(' *Max-',temp[i,j,k,l],chr(176),'C')

Day wise temperature:
	November / Week-1
Monday
 *Min-6 ° C
 *Max- 23 ° C
Tuesday
 *Min-14 ° C
 *Max- 20 ° C
Wednesday
 *Min-6 ° C
 *Max- 27 ° C
Thursday
 *Min-14 ° C
 *Max- 22 ° C
Friday
 *Min-8 ° C
 *Max- 22 ° C
Saturday
 *Min-6 ° C
 *Max- 32 ° C
Sunday
 *Min-14 ° C
 *Max- 29 ° C
	December / Week-1
Monday
 *Min-8 ° C
 *Max- 23 ° C
Tuesday
 *Min-14 ° C
 *Max- 20 ° C
Wednesday
 *Min-6 ° C
 *Max- 27 ° C
Thursday
 *Min-14 ° C
 *Max- 22 ° C
Friday
 *Min-8 ° C
 *Max- 22 ° C
Saturday
 *Min-6 ° C
 *Max- 32 ° C
Sunday
 *Min-14 ° C
 *Max- 29 ° C
	January / Week-1
Monday
 *Min-9 ° C
 *Max- 23 ° C
Tuesday
 *Min-14 ° C
 *Max- 20 ° C
Wednesday
 *Min-6 ° C
 *Max- 27 ° C
Thursday
 *Min-14 ° C
 *Max- 22 ° C
Friday
 *Min-8 ° C
 *Max- 22 ° C
Saturday
 *Min-6 ° C
 *Max- 32 ° C
Sunday
 *Min-14 ° C
 *Max- 29 ° C
	February / Week-1
Monday
 *Min-6 ° C
 *Max- 23 ° C
Tuesday
 *Min-14 ° C
 *Max- 20 ° C
Wednesday
 *Min-6 ° C
 *Max- 27 ° C
Thursday
 *Min-14 ° C
 *Max- 22 ° C
Friday
 *Min-8 ° C
 *Max- 22 ° C
Satu

In [61]:
print(f'# In the format of [month[week[tuesday[min,max]]]] :\n{temp[:,:,1]}')

# In the format of [month[week[tuesday[min,max]]]] :
[[[14 20]
  [12 29]
  [12 18]
  [ 0 12]]

 [[14 20]
  [12 29]
  [12 18]
  [ 0 12]]

 [[14 20]
  [12 29]
  [12 18]
  [ 0 12]]

 [[14 20]
  [12 29]
  [12 18]
  [ 0 12]]]


In [176]:
print('Temperature of the day:')

# Shape of temp is (4,4,7,2)
for i in range(temp.shape[0]): # iterate over Months
    print(f'\t{month[i]}')
    
    for j in range(temp.shape[1]): # iterate over Weeks
        print(f'\tWeek-{j+1}')
        
        k=1   # iterate over Days.Here,only Tuesday required.
        print('Tuesday:')
        
        # 'l' iterate over Temperature
        l=0   # access min
        print('Min- ',temp[i,j,k,l],chr(176),'C')
        
        l=l+1  # access max
        print('Max- ',temp[i,j,k,l],chr(176),'C')

Temperature of the day:
	November
	Week-1
Tuesday:
Min-  14 ° C
Max-  20 ° C
	Week-2
Tuesday:
Min-  12 ° C
Max-  29 ° C
	Week-3
Tuesday:
Min-  12 ° C
Max-  18 ° C
	Week-4
Tuesday:
Min-  0 ° C
Max-  12 ° C
	December
	Week-1
Tuesday:
Min-  14 ° C
Max-  20 ° C
	Week-2
Tuesday:
Min-  12 ° C
Max-  29 ° C
	Week-3
Tuesday:
Min-  12 ° C
Max-  18 ° C
	Week-4
Tuesday:
Min-  0 ° C
Max-  12 ° C
	January
	Week-1
Tuesday:
Min-  14 ° C
Max-  20 ° C
	Week-2
Tuesday:
Min-  12 ° C
Max-  29 ° C
	Week-3
Tuesday:
Min-  12 ° C
Max-  18 ° C
	Week-4
Tuesday:
Min-  0 ° C
Max-  12 ° C
	February
	Week-1
Tuesday:
Min-  14 ° C
Max-  20 ° C
	Week-2
Tuesday:
Min-  12 ° C
Max-  29 ° C
	Week-3
Tuesday:
Min-  12 ° C
Max-  18 ° C
	Week-4
Tuesday:
Min-  0 ° C
Max-  12 ° C


In [62]:
print(f'# In the format of [month[week[day wise max temp]]] :\n{temp[1:4:2,:,:,1]}')

# In the format of [month[week[day wise max temp]]] :
[[[23 20 27 22 22 32 29]
  [27 29 29 23 31 30 30]
  [21 18 12 20 27 28 19]
  [15 12 18 24 20 24 17]]

 [[23 20 27 22 22 32 29]
  [27 29 29 23 31 30 30]
  [21 18 12 20 27 28 19]
  [15 12 18 24 20 24 17]]]


In [79]:
print('Maximum temperature of the day:')

# Shape of temp is (4,4,7,2)
for i in range(1,4,2): # iterate over Months.Need only Dec & Feb
    print(f'\t{month[i]}')
    
    for j in range(temp.shape[1]): # iterate over Weeks
        print('\tWeek-',j+1)
        
        for k in range(temp.shape[2]): # iterate over Days
            # print max temperature  
            print(f'{day[k]}-',temp[i,j,k,1],chr(176),'C')

Maximum temperature of the day:
	December
	Week- 1
Monday- 23 ° C
Tuesday- 20 ° C
Wednesday- 27 ° C
Thursday- 22 ° C
Friday- 22 ° C
Saturday- 32 ° C
Sunday- 29 ° C
	Week- 2
Monday- 27 ° C
Tuesday- 29 ° C
Wednesday- 29 ° C
Thursday- 23 ° C
Friday- 31 ° C
Saturday- 30 ° C
Sunday- 30 ° C
	Week- 3
Monday- 21 ° C
Tuesday- 18 ° C
Wednesday- 12 ° C
Thursday- 20 ° C
Friday- 27 ° C
Saturday- 28 ° C
Sunday- 19 ° C
	Week- 4
Monday- 15 ° C
Tuesday- 12 ° C
Wednesday- 18 ° C
Thursday- 24 ° C
Friday- 20 ° C
Saturday- 24 ° C
Sunday- 17 ° C
	February
	Week- 1
Monday- 23 ° C
Tuesday- 20 ° C
Wednesday- 27 ° C
Thursday- 22 ° C
Friday- 22 ° C
Saturday- 32 ° C
Sunday- 29 ° C
	Week- 2
Monday- 27 ° C
Tuesday- 29 ° C
Wednesday- 29 ° C
Thursday- 23 ° C
Friday- 31 ° C
Saturday- 30 ° C
Sunday- 30 ° C
	Week- 3
Monday- 21 ° C
Tuesday- 18 ° C
Wednesday- 12 ° C
Thursday- 20 ° C
Friday- 27 ° C
Saturday- 28 ° C
Sunday- 19 ° C
	Week- 4
Monday- 15 ° C
Tuesday- 12 ° C
Wednesday- 18 ° C
Thursday- 24 ° C
Friday- 20 ° C
Satu

In [65]:
print(f'# in the formate of [week,day]\n# wk1=0,wk2=1,wk3=2,wk4=3\n# mon=0,tue=1,wed=2,thus=3,fri=4,sat=5,sun=6\n{np.argwhere(temp[0,:,:,0]<8)}')

# in the formate of [week,day]
# wk1=0,wk2=1,wk3=2,wk4=3
# mon=0,tue=1,wed=2,thus=3,fri=4,sat=5,sun=6
[[0 0]
 [0 2]
 [0 5]
 [1 0]
 [1 3]
 [2 0]
 [2 2]
 [3 0]
 [3 1]
 [3 2]
 [3 6]]


In [228]:
print('Below 8 Degrees in November')

# Shape of temp is (4,4,7,2)
for j in range(temp.shape[1]): # iterate over Weeks
    
    for k in range(temp.shape[2]): # iterate over Days
        
        if temp[0,j,k,0]<8: # find the temperatures below 8 degrees
           print(f'Week- {j+1} {day[k]}')

Below 8 Degrees in November
Week- 1 Monday
Week- 1 Wednesday
Week- 1 Saturday
Week- 2 Monday
Week- 2 Thursday
Week- 3 Monday
Week- 3 Wednesday
Week- 4 Monday
Week- 4 Tuesday
Week- 4 Wednesday
Week- 4 Sunday


In [69]:
print('Above 20 Degrees in Dec & Jan')

for i in [1,2]: # iterate over Months.Need only Dec & Jan
    
     for j in range(4): # iterate over Weeks
            
            if np.any(temp[i,j]>20): # To find the temperatures above 20 deg
                print(f'{month[i]} Week-{j+1}')

Above 20 Degrees in Dec & Jan
December Week-1
December Week-2
December Week-3
December Week-4
January Week-1
January Week-2
January Week-3
January Week-4


In [180]:
if np.any(temp<0) or np.any(temp>30): # Checking if there is any absurd value 
    print('Yes.Absurd value is present.')
else:
    print('No any absurd value.')

Yes.Absurd value is present.


In [77]:
print('# in the format of [month,week,day,temp]')
print('# nov=0,dec=1,jan=2,feb=3\n# wk1=0,wk2=1,wk3=2,wk4=3\n# mon=0,tue=1,wed=2,thus=3,fri=4,sat=5,sun=6\# nmin=0,max=1')
print(np.argwhere(temp<0),'\n',np.argwhere(temp>30))

# in the format of [month,week,day,temp]
# nov=0,dec=1,jan=2,feb=3
# wk1=0,wk2=1,wk3=2,wk4=3
# mon=0,tue=1,wed=2,thus=3,fri=4,sat=5,sun=6\# nmin=0,max=1
[[0 1 3 0]
 [0 2 2 0]
 [0 3 0 0]
 [1 1 3 0]
 [1 2 2 0]
 [1 3 0 0]
 [2 1 4 0]
 [2 2 2 0]
 [2 3 0 0]
 [3 1 3 0]
 [3 2 2 0]
 [3 3 0 0]] 
 [[0 0 5 1]
 [0 1 6 1]
 [1 0 5 1]
 [1 1 4 1]
 [2 0 5 1]
 [2 1 4 1]
 [3 0 5 1]
 [3 1 4 1]]


In [229]:
for i in range(temp.shape[0]): # iterate over Months
    
    for j in range(temp.shape[1]): # iterate over Weeks
        
        for k in range(temp.shape[2]): # iterate over Days
            
            if temp[i,j,k,0]<0: # find the min absurd temperatures which is below 0 deg
                
                temp[i,j,k,0]=np.mean(temp[i,j,:,0])
                print(temp[i,j,k,0])
            
            if temp[i,j,k,1]>30: # find the max absurd temperatures which is above 30 deg
                temp[i,j,k,1]=np.mean(temp[i,j,:,1])
                print(temp[i,j,k,1])

25
7
26
11
5
25
7
28
10
5
25
7
28
11
5
25
7
28
11
5


In [183]:
for i in range(1,4): # winter months of jaipur- Dec,Jan & Feb
   
    mean=[] # To Store Weekly mean max temp  
    a=np.mean(temp[i],axis=1) # compute mean weekly temp
    b=np.mean(a,axis=0) # compute mean max temp
    mean.append(b[1]) # Storing montly mean max temp
print(f'Average max temperature for the winter month: {np.round(np.mean(mean),2)}',chr(176),'c')

Average max temperature for the winter month: 23.18 ° c


In [35]:
a=np.mean(temp[1:4],axis=1) # calculate mean weekly temp 
b=np.mean(a,axis=1)
c=np.mean(b,axis=0)
print(f'Average max temperature for the winter month: {np.round(c[1],2)}',chr(176),'c')

Average max temperature for the winter month: 23.18 ° c


In [230]:
a = [] # To store Weekly average minimum temperatures 
  
print('Average minimum temperatures for December:')

for i in range(temp.shape[1]):# iterate over weeks
    b=np.mean(temp[1,i],axis=0) # December is the second month
    print(f'Week {i+1}- {np.round(b[0],1)}',chr(176),'C')

Average minimum temperatures for December:
Week 1- 10.0 ° C
Week 2- 10.7 ° C
Week 3- 13.3 ° C
Week 4- 6.0 ° C


In [185]:
b=np.mean(temp[1],axis=1)
c=b.reshape(8)
print(np.round(c[:8:2],1))

[10.  11.9 13.6  5.6]


In [187]:
# Temperature data for December and January
# Compute the mean temperature
print(f'Overall avg temp for the months Dec & Jan: {np.round(np.mean(temp[1:3]),2)}',chr(176),'C')

Overall avg temp for the months Dec & Jan: 16.61 ° C


In [197]:
for i in range(1,3): # iterate over Dec & Jan 
    print(f'Least temperature in {month[i]}- {np.min(temp[i])}',chr(176),'C')
    
    min_temp=np.min(temp[i]) # Finding min temp
    frmt=np.argwhere(temp[i] == min_temp) # indexing min temp
    
    print(f'{day[frmt[0,1]]}/Week-{frmt[0,0]+1}/{month[i]}') #frmt[week,day,temp]

Least temperature in December- -15 ° C
Thursday/Week-2/December
Least temperature in January- -13 ° C
Friday/Week-2/January


In [195]:
print(f'Max temperature in Feb - {np.max(temp[3])}',chr(176),'C') #Feb is the fourth month

max_temp=np.max(temp[3]) # Finding max temp
frmt=np.argwhere(temp[3] == max_temp) # indexing max temp 

print(f'{day[frmt[0,1]]}/Week-{frmt[0,0]+1}/Feb') #frmt[week,day,temp]

Max temperature in Feb - 32 ° C
Saturday/Week-1/Feb


In [222]:
loc=np.argwhere((temp[0,:,:,1])<(np.mean(temp[0])))
for i in range(loc.shape[0]):
    print(f'Week-{loc[i,0]+1} {day[loc[i,1]]}')

Week-3 Wednesday
Week-4 Monday
Week-4 Tuesday


In [253]:
# total 4 months & each month has 4 weeks & each week has 56 temp values 
# reshape the array to shape (4,56) 
print(temp.reshape(4,56))

[[  6  23  14  20   6  27  14  22   8  22   6  32  14  29   7  27  12  29
   11  29 -13  23  15  28  15  20   8  32   5  21  12  18  -1  12  12  20
   25  29  17  22  12  19  -2  15   0  12   2  18  13  24  10  16  12  18
    0  17]
 [  8  23  14  20   6  27  14  22   8  22   6  32  14  29   7  27  12  29
   11  29 -15  23  15  31  15  30   8  30   5  21  12  18 -12  12  12  20
   25  27  17  28  12  19  -2  15   0  12   2  18  13  24  10  20  12  24
    0  17]
 [  9  23  14  20   6  27  14  22   8  22   6  32  14  29   7  27  12  29
   11  29  15  23 -13  31  15  30   8  30   5  21  12  18  -1  12  12  20
   25  27  17  28  12  19  -2  15   0  12   2  18  13  24  10  20  12  24
    0  17]
 [  6  23  14  20   6  27  14  22   8  22   6  32  14  29   7  27  12  29
   11  29 -13  23  15  31  15  30   8  30   5  21  12  18  -1  12  12  20
   25  27  17  28  12  19  -2  15   0  12   2  18  13  24  10  20  12  24
    0  17]]


In [21]:
#  formula F = (C × 9/5) + 32 
print(f'Temp data in Fahrenheit:\n{temp*(9/5)+32}')

Temp data in Fahrenheit:
[[[[42.8 73.4]
   [57.2 68. ]
   [42.8 80.6]
   [57.2 71.6]
   [46.4 71.6]
   [42.8 89.6]
   [57.2 84.2]]

  [[44.6 80.6]
   [53.6 84.2]
   [51.8 84.2]
   [ 8.6 73.4]
   [59.  82.4]
   [59.  68. ]
   [46.4 89.6]]

  [[41.  69.8]
   [53.6 64.4]
   [30.2 53.6]
   [53.6 68. ]
   [77.  84.2]
   [62.6 71.6]
   [53.6 66.2]]

  [[28.4 59. ]
   [32.  53.6]
   [35.6 64.4]
   [55.4 75.2]
   [50.  60.8]
   [53.6 64.4]
   [32.  62.6]]]


 [[[46.4 73.4]
   [57.2 68. ]
   [42.8 80.6]
   [57.2 71.6]
   [46.4 71.6]
   [42.8 89.6]
   [57.2 84.2]]

  [[44.6 80.6]
   [53.6 84.2]
   [51.8 84.2]
   [ 5.  73.4]
   [59.  87.8]
   [59.  86. ]
   [46.4 86. ]]

  [[41.  69.8]
   [53.6 64.4]
   [10.4 53.6]
   [53.6 68. ]
   [77.  80.6]
   [62.6 82.4]
   [53.6 66.2]]

  [[28.4 59. ]
   [32.  53.6]
   [35.6 64.4]
   [55.4 75.2]
   [50.  68. ]
   [53.6 75.2]
   [32.  62.6]]]


 [[[48.2 73.4]
   [57.2 68. ]
   [42.8 80.6]
   [57.2 71.6]
   [46.4 71.6]
   [42.8 89.6]
   [57.2 84.2]]

  [[44.6

In [19]:
# temp[1] iterate dec months data 
# calculate the average min & max temp weekly in Dec
avg=np.mean(temp[1],axis=1)

# calculate  overall average weekly temp
avg2=np.mean(avg,axis=1) 

# sort and print the result in descending order
print(f'Dec month average weekly temp in descending order: {np.round(np.sort(avg2)[::-1],1)}')

Dec month average weekly temp in descending order: [18.  17.5 15.4 11.8]


In [124]:
#selecting the temp of the first three days of each month
temp_3days=temp[:,:,:3] 

x=np.mean(temp_3days,axis=2) # calculate 3 days avg weekly temp
y=np.mean(x,axis=1) # calculate each 3 days avg weekly temp
z=np.mean(y,axis=1) # calculate 3 days avg weekly temp for each month

ovral_mean=np.mean(temp[1:4]) # calculate overall avg temp of wintere
base=np.append(z,ovral_mean) # adding base value into array 

print(np.sort(base)[::-1]) # print in descending order

[15.82738095 13.58333333 13.45833333 13.45833333 13.08333333]


In [102]:
# store the difference between the temp
diff=(temp[:,:,:,1]-temp[:,:,:,0]).reshape(4,4,7,1) # reshape it as the same as base array
print('Difference Between Dilay temperatures: \n',diff)

Difference Between Dilay temperatures: 
 [[[[17]
   [ 6]
   [21]
   [ 8]
   [14]
   [26]
   [15]]

  [[20]
   [17]
   [18]
   [36]
   [13]
   [ 5]
   [24]]

  [[16]
   [ 6]
   [13]
   [ 8]
   [ 4]
   [ 5]
   [ 7]]

  [[17]
   [12]
   [16]
   [11]
   [ 6]
   [ 6]
   [17]]]


 [[[15]
   [ 6]
   [21]
   [ 8]
   [14]
   [26]
   [15]]

  [[20]
   [17]
   [18]
   [38]
   [16]
   [15]
   [22]]

  [[16]
   [ 6]
   [24]
   [ 8]
   [ 2]
   [11]
   [ 7]]

  [[17]
   [12]
   [16]
   [11]
   [10]
   [12]
   [17]]]


 [[[14]
   [ 6]
   [21]
   [ 8]
   [14]
   [26]
   [15]]

  [[20]
   [17]
   [18]
   [ 8]
   [44]
   [15]
   [22]]

  [[16]
   [ 6]
   [13]
   [ 8]
   [ 2]
   [11]
   [ 7]]

  [[17]
   [12]
   [16]
   [11]
   [10]
   [12]
   [17]]]


 [[[17]
   [ 6]
   [21]
   [ 8]
   [14]
   [26]
   [15]]

  [[20]
   [17]
   [18]
   [36]
   [16]
   [15]
   [22]]

  [[16]
   [ 6]
   [13]
   [ 8]
   [ 2]
   [11]
   [ 7]]

  [[17]
   [12]
   [16]
   [11]
   [10]
   [12]
   [17]]]]


In [145]:
wint_maxdiff=[]
for i in range(1,4):
    for j in range(0,4):
        for k in range(0,6):
            x=temp[i,j,k+1,1]-temp[i,j,k,1]
            wint_maxdiff.append(x)
print(wint_maxdiff)

[-3, 7, -5, 0, 10, -3, 2, 0, -6, 8, -1, 0, -3, -6, 8, 7, 1, -9, -3, 6, 6, -4, 4, -7, -3, 7, -5, 0, 10, -3, 2, 0, -6, 8, -1, 0, -3, -6, 8, 7, 1, -9, -3, 6, 6, -4, 4, -7, -3, 7, -5, 0, 10, -3, 2, 0, -6, 8, -1, 0, -3, -6, 8, 7, 1, -9, -3, 6, 6, -4, 4, -7]


In [167]:
wint_mindiff=[]
for i in range(1,4):
    for j in range(0,4):
        for k in range(0,6):
            x=temp[i,j,k+1,0]-temp[i,j,k,0]
            wint_mindiff.append(x)
print(wint_mindiff)

[6, -8, 8, -6, -2, 8, 5, -1, -26, 30, 0, -7, 7, -24, 24, 13, -8, -5, 2, 2, 11, -3, 2, -12, 5, -8, 8, -6, -2, 8, 5, -1, 4, -28, 28, -7, 7, -13, 13, 13, -8, -5, 2, 2, 11, -3, 2, -12, 8, -8, 8, -6, -2, 8, 5, -1, -24, 28, 0, -7, 7, -13, 13, 13, -8, -5, 2, 2, 11, -3, 2, -12]


In [162]:
array=np.array((wint_maxdiff,wint_mindiff))
array

array([[ -3,   7,  -5,   0,  10,  -3,   2,   0,  -6,   8,  -1,   0,  -3,
         -6,   8,   7,   1,  -9,  -3,   6,   6,  -4,   4,  -7,  -3,   7,
         -5,   0,  10,  -3,   2,   0,  -6,   8,  -1,   0,  -3,  -6,   8,
          7,   1,  -9,  -3,   6,   6,  -4,   4,  -7,  -3,   7,  -5,   0,
         10,  -3,   2,   0,  -6,   8,  -1,   0,  -3,  -6,   8,   7,   1,
         -9,  -3,   6,   6,  -4,   4,  -7],
       [  6,  -8,   8,  -6,  -2,   8,   5,  -1, -26,  30,   0,  -7,   7,
        -24,  24,  13,  -8,  -5,   2,   2,  11,  -3,   2, -12,   5,  -8,
          8,  -6,  -2,   8,   5,  -1,   4, -28,  28,  -7,   7, -13,  13,
         13,  -8,  -5,   2,   2,  11,  -3,   2, -12,   8,  -8,   8,  -6,
         -2,   8,   5,  -1, -24,  28,   0,  -7,   7, -13,  13,  13,  -8,
         -5,   2,   2,  11,  -3,   2, -12]])